name: client-test

on:
  pull_request:
    branches:
      - develop
    paths:
      - "**"

jobs:
  typecheck:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node.js 📦
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Typecheck 👀
        run: yarn workspace client typecheck
